[package]
name = "packet-counter"
version = "0.1.0"
edition = "2021"

[dependencies]
xdp = { path = "../../crates/xdp" }
bpf = { path = "../../crates/bpf" }
xdp-sys = { path = "../../crates/xdp-sys" }
argh = "0.1.12"
libc = "0.2.148"
packet = "0.1.4"
byteorder = "1.4.3"